---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: capacitor-secret-composer
  namespace: utilities
  labels:
    secret-composer.controller/install: "true"
spec:
  type: Static
  defaultValues:
    namespace: flux-system
    cron_schedule: "* * * * *"
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: oauth2-proxy-creds-secret-composer
#   namespace: flux-system
#   labels:
#     secret-composer.controller/enabled: "true"
# data:
#   sourceSecret: capacitor-oidc-credentials
#   targetSecret: oauth2-proxy-creds
#
#   map.client-id: client_id
#   map.client-secret: client_secret
#
#   gen.cookie-secret: "true"
