---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: pocket-id-garage-key
  namespace: pocket-id-system
spec:
  clusterRef:
    name: garage
    namespace: garage-system
  bucketPermissions:
    - bucketRef: pocket-id-database
      read: true
      write: true
    - bucketRef: pocket-id-files
      read: true
      write: true
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: pocket-id-database
  namespace: pocket-id-system
spec:
  clusterRef:
    name: garage
    namespace: garage-system
  quotas:
    maxSize: 8Gi
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: pocket-id-files
  namespace: pocket-id-system
spec:
  clusterRef:
    name: garage
    namespace: garage-system
  quotas:
    maxSize: 8Gi
