---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-garage-data-staging
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 32Gi
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      storage: vmpool
    volumeHandle: armada/crimson/vmpool/vm-9999-pvc-garage-data-staging
  storageClassName: vmpool-persistent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-staging
  namespace: garage-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vmpool-persistent
  volumeName: pvc-garage-data-staging
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-garage-metadata-staging
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 32Gi
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: xfs
    volumeAttributes:
      storage: vmpool
    volumeHandle: armada/crimson/vmpool/vm-9999-pvc-garage-metadata-staging
  storageClassName: vmpool-persistent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-metadata-staging
  namespace: garage-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vmpool-persistent
  volumeName: pvc-garage-metadata-staging
