---
apiVersion: v1
kind: Namespace
metadata:
  name: garage-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: garage-operator
  namespace: garage-system
spec:
  interval: 24h
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage-operator
  namespace: garage-system
spec:
  interval: 30m
  upgrade:
    crds: CreateReplace
  chartRef:
    kind: OCIRepository
    name: garage-operator
    namespace: garage-system
  # https://github.com/rajsinghtech/garage-operator/blob/main/charts/garage-operator/values.yaml
  # values:
  #   cosi:
  #     enabled: true
