---
apiVersion: v1
kind: Namespace
metadata:
  name: pocket-id-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: pocket-id-operator
  namespace: pocket-id-system
spec:
  interval: 24h
  url: oci://ghcr.io/aclerici38/charts/pocket-id-operator
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
  namespace: pocket-id-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
    namespace: pocket-id-system
  # https://github.com/aclerici38/pocket-id-operator/blob/main/dist/chart/values.yaml
  values:
    instance:
      enabled: false
